"""Create media catalog schema.

Revision ID: 14fde284fd0d
Revises:
Create Date: 2026-09-13 21:13:45.298942
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "14fde284fd0d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table("genres", sa.Column("name", sa.String(length=100), nullable=False), sa.PrimaryKeyConstraint("name"))
    op.create_table(
        "media_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("original_title", sa.String(length=500), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.CheckConstraint("media_type IN ('movie', 'tv_show')", name="ck_media_items_type"),
        sa.CheckConstraint("runtime_minutes IS NULL OR runtime_minutes > 0", name="ck_media_items_runtime_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_items_media_type"), "media_items", ["media_type"], unique=False)
    op.create_index(op.f("ix_media_items_title"), "media_items", ["title"], unique=False)
    op.create_table(
        "artwork",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("artwork_type", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artwork_media_id"), "artwork", ["media_id"], unique=False)
    op.create_table(
        "external_ids",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_id", "namespace", name="uq_external_ids_media_namespace"),
        sa.UniqueConstraint("namespace", "value", name="uq_external_ids_namespace_value"),
    )
    op.create_index(op.f("ix_external_ids_media_id"), "external_ids", ["media_id"], unique=False)
    op.create_table(
        "media_countries",
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("media_id", "country_code"),
    )
    op.create_table(
        "media_genres",
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("genre_name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_name"],
            ["genres.name"],
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("media_id", "genre_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media_genres")
    op.drop_table("media_countries")
    op.drop_index(op.f("ix_external_ids_media_id"), table_name="external_ids")
    op.drop_table("external_ids")
    op.drop_index(op.f("ix_artwork_media_id"), table_name="artwork")
    op.drop_table("artwork")
    op.drop_index(op.f("ix_media_items_title"), table_name="media_items")
    op.drop_index(op.f("ix_media_items_media_type"), table_name="media_items")
    op.drop_table("media_items")
    op.drop_table("genres")
    op.drop_table("countries")
    # ### end Alembic commands ###
