"""Application-layer contracts and services."""

from media_recommender.application.availability import (
    AvailabilityOffer,
    AvailabilityProvider,
    AvailabilityRefreshResult,
    AvailabilityRefreshService,
    AvailabilityRefreshStatus,
    AvailabilityRepository,
)
from media_recommender.application.catalog import MediaCatalog, MediaCatalogReader, MediaCatalogWriter
from media_recommender.application.errors import (
    CatalogServiceError,
    InvalidProviderResultError,
    MediaDetailsNotFoundError,
    MetadataProviderNotConfiguredError,
)
from media_recommender.application.identity import (
    MatchKind,
    MatchReason,
    MediaIdentityCandidate,
    MediaIdentityEnricher,
    MediaIdentityResolver,
    MediaMatch,
    normalize_title,
)
from media_recommender.application.imports import (
    IdentityResolver,
    ImportRecordResult,
    ImportRecordStatus,
    InvalidImportRecord,
    PersonalImportKind,
    PersonalImportRecord,
    PersonalImportResult,
    PersonalMediaImportService,
)
from media_recommender.application.library import (
    InvalidLibraryItem,
    LibraryItemResult,
    LibraryItemSnapshot,
    LibraryItemStatus,
    LibrarySynchronizationResult,
    LibrarySynchronizationService,
)
from media_recommender.application.personal import PersonalMediaRepository, ProfileRepository
from media_recommender.application.providers import MediaSearchResult, MetadataProvider
from media_recommender.application.ranking import (
    ConstraintMatch,
    ConstraintMatchKind,
    KnownAvailability,
    RankedRecommendation,
    RankingReason,
    RankingReasonKind,
    RankingWeights,
    RecommendationResult,
    RecommendationService,
    RecommendationWarning,
    RecommendationWarningKind,
)
from media_recommender.application.recommendations import (
    AvailabilityCriterion,
    AvailabilitySourceKind,
    FilterExclusion,
    FilterReason,
    GenreMatch,
    RecommendationCandidate,
    RecommendationCriteria,
    RecommendationDataSource,
    RecommendationDecision,
    RecommendationFilterResult,
    RecommendationFilterService,
    WatchRequirement,
    apply_recommendation_filters,
    availability_matches,
    preference_matches,
    preference_measure,
)
from media_recommender.application.regions import ProductionRegion, production_region
from media_recommender.application.services import CatalogService

__all__ = [
    "AvailabilityCriterion",
    "AvailabilityOffer",
    "AvailabilityProvider",
    "AvailabilityRefreshResult",
    "AvailabilityRefreshService",
    "AvailabilityRefreshStatus",
    "AvailabilityRepository",
    "AvailabilitySourceKind",
    "CatalogService",
    "CatalogServiceError",
    "ConstraintMatch",
    "ConstraintMatchKind",
    "FilterExclusion",
    "FilterReason",
    "GenreMatch",
    "IdentityResolver",
    "ImportRecordResult",
    "ImportRecordStatus",
    "InvalidImportRecord",
    "InvalidLibraryItem",
    "InvalidProviderResultError",
    "KnownAvailability",
    "LibraryItemResult",
    "LibraryItemSnapshot",
    "LibraryItemStatus",
    "LibrarySynchronizationResult",
    "LibrarySynchronizationService",
    "MatchKind",
    "MatchReason",
    "MediaCatalog",
    "MediaCatalogReader",
    "MediaCatalogWriter",
    "MediaDetailsNotFoundError",
    "MediaIdentityCandidate",
    "MediaIdentityEnricher",
    "MediaIdentityResolver",
    "MediaMatch",
    "MediaSearchResult",
    "MetadataProvider",
    "MetadataProviderNotConfiguredError",
    "PersonalImportKind",
    "PersonalImportRecord",
    "PersonalImportResult",
    "PersonalMediaImportService",
    "PersonalMediaRepository",
    "ProductionRegion",
    "ProfileRepository",
    "RankedRecommendation",
    "RankingReason",
    "RankingReasonKind",
    "RankingWeights",
    "RecommendationCandidate",
    "RecommendationCriteria",
    "RecommendationDataSource",
    "RecommendationDecision",
    "RecommendationFilterResult",
    "RecommendationFilterService",
    "RecommendationResult",
    "RecommendationService",
    "RecommendationWarning",
    "RecommendationWarningKind",
    "WatchRequirement",
    "apply_recommendation_filters",
    "availability_matches",
    "normalize_title",
    "preference_matches",
    "preference_measure",
    "production_region",
]
